name: Ejecutar Código Python Cada X Horas

on:
  schedule:
    # Ejecutar cada 3 horas
    - cron: "0 * * * *"

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Ejecutar script Python
      run: python script.py
